// What Вещи are made of. The behaviour lives in core/sw.js.

importScripts("../../core/sw.js");

life.serve({
  key: "things",
  shell: [
    "./",
    "./index.html",
    "./app.js",
    "./manifest.js",
    "./manifest.webmanifest",
    "./lib/model.js",
    "./lib/store.js",
    "./screens/things.js",
    "./screens/thing.js",
    "./screens/warranty.js",
    "./screens/settings.js",
    "../../design/app.css",
    "../../design/things.css",
    "../../core/app.js",
    "../../core/shell.js",
    "../../core/dom.js",
    "../../core/icons.js",
    "../../core/state.js",
    "../../core/store.js",
    "../../core/sync.js",
    "../../core/github.js",
    "../../core/time.js",
    "../../core/money.js",
    "../../core/vault.js",
    "../../core/log.js",
    "../../core/registry.js",
    "../../core/reach.js",
    "../../core/keys.js",
    "../../core/health.js",
    "../../core/screens/card.js",
    "../../core/screens/settings.js",
  ],
});
